// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA7L41mADoH7qqib4ztghdQuSrOAwxZLw',
    appId: '1:206849971594:android:34ec40c0d68df02332a473',
    messagingSenderId: '206849971594',
    projectId: 'task-manager-76140',
    storageBucket: 'task-manager-76140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8ee1aIErEIrzLXQACzxJ7Q-G2AY4nj4',
    appId: '1:206849971594:ios:f37e926d1427d16b32a473',
    messagingSenderId: '206849971594',
    projectId: 'task-manager-76140',
    storageBucket: 'task-manager-76140.firebasestorage.app',
    iosClientId: '206849971594-gqq3umacdkg9qde5aa5m192k1bbfna6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.accessApp',
  );

}