// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA7L41mADoH7qqib4ztghdQuSrOAwxZLw',
    appId: '1:206849971594:android:34ec40c0d68df02332a473',
    messagingSenderId: '206849971594',
    projectId: 'task-manager-76140',
    storageBucket: 'task-manager-76140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8ee1aIErEIrzLXQACzxJ7Q-G2AY4nj4',
    appId: '1:206849971594:ios:f37e926d1427d16b32a473',
    messagingSenderId: '206849971594',
    projectId: 'task-manager-76140',
    storageBucket: 'task-manager-76140.firebasestorage.app',
    iosClientId:
        '206849971594-gqq3umacdkg9qde5aa5m192k1bbfna6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.accessApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_API_KEY',
      defaultValue: 'AIzaSyBA7L41mADoH7qqib4ztghdQuSrOAwxZLw',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_WEB_APP_ID',
      defaultValue: '1:206849971594:web:34ec40c0d68df02332a473',
    ),
    messagingSenderId: String.fromEnvironment(
      'FIREBASE_WEB_MESSAGING_SENDER_ID',
      defaultValue: '206849971594',
    ),
    projectId: String.fromEnvironment(
      'FIREBASE_WEB_PROJECT_ID',
      defaultValue: 'task-manager-76140',
    ),
    authDomain: String.fromEnvironment(
      'FIREBASE_WEB_AUTH_DOMAIN',
      defaultValue: 'task-manager-76140.firebaseapp.com',
    ),
    storageBucket: String.fromEnvironment(
      'FIREBASE_WEB_STORAGE_BUCKET',
      defaultValue: 'task-manager-76140.firebasestorage.app',
    ),
  );
}
